[package]
name = "opendalfs"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
pyo3 = { version = "0.22.2", features = ["gil-refs"] }
opendal = "0.47.3"