[package]
name = "opendalfs-service-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
pyo3.workspace = true
opendal = { workspace = true, features = ["services-memory"]}
opendalfs-core.workspace = true
