name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        # Install build dependencies first
        pip install maturin build twine ruff pytest pytest-cov

    - name: Build service packages
      run: |
        source .venv/bin/activate
        # Build and install service packages
        maturin develop -m crates/service-memory/Cargo.toml
        maturin develop -m crates/service-s3/Cargo.toml

    - name: Install main package
      run: |
        source .venv/bin/activate
        # Now install the main package with all extras
        pip install -e ".[all]"

    - name: Check code format
      run: |
        source .venv/bin/activate
        ruff format . --check

    - name: Build packages for distribution
      run: |
        source .venv/bin/activate
        maturin build -m crates/service-memory/Cargo.toml
        maturin build -m crates/service-s3/Cargo.toml
        python -m build

    - name: Check dist files
      run: |
        source .venv/bin/activate
        twine check dist/*
