name: Package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
      - 'docs/**'

jobs:
  check-rust:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  check-python:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: pip install ruff build twine

      - name: Check format
        run: ruff format . --check

      - name: Check style
        run: ruff check .

  check-pyo3:
    name: PyO3 Service Builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["memory", "s3"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: "crates/service-${{ matrix.service }}"

  build-dist:
    name: Build Distribution
    needs: [check-rust, check-python, check-pyo3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Python package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Verify package
        run: |
          pip install twine
          twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error 