name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Start MinIO
      run: |
        docker compose -f tests/docker/docker-compose.yml up -d
        # Wait for MinIO to be ready
        sleep 10

    - name: Create virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        # Install build dependencies first
        pip install maturin pytest pytest-cov

    - name: Build service packages
      run: |
        source .venv/bin/activate
        # Build and install service packages
        maturin develop -m crates/service-memory/Cargo.toml
        maturin develop -m crates/service-s3/Cargo.toml

    - name: Install main package
      run: |
        source .venv/bin/activate
        # Now install the main package with test extras
        pip install -e ".[test]"

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest -v --cov=opendalfs --cov-report=xml
      env:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin

    - name: Stop MinIO
      if: always()
      run: docker compose -f tests/docker/docker-compose.yml down 
